[workspace]
authors = ["Hannes Neuschmidt <hannes.neuschmidt@brockmann-consult.de>"]
channels = ["conda-forge"]
name = "heatwise-interoperability-demonstration"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render-notebooks = { cmd = ["quarto", "render", "--profile", "demonstration", "--to", "ipynb", "--output-dir", "../_notebooks"], default-environment = "dev", cwd="docs"}
render-website = { cmd = ["quarto", "render", "--profile", "book", "--output-dir", "../_site"], default-environment = "dev", cwd="docs"}
render-pdf = { cmd = ["quarto", "render", "--profile", "book", "--to", "typst", "--output-dir", "../_book_pdf"], default-environment = "dev", cwd="docs"}
preview = { cmd = ["quarto", "preview", "--profile", "book", "--output-dir", "../_site_preview"], default-environment = "dev", cwd="docs"}

clean-docs = { cmd = ["rm", "-rf", "_notebooks", "_site", "_book_pdf", "_freeze", "_site_preview"], cwd="."}
clean = { cmd = ["rm", "-rf", "software", "inputs", "outputs", "application-packages"]}

stage = { cmd = ["stage.sh"] }


show-notebooks = { cmd = ["jupyter", "lab"], default-environment = "dev", cwd="_notebooks/software_products"}

[dependencies]
bash_kernel = ">=0.10.0,<0.11"
geopandas = ">=1.1.4,<2"
pystac = ">=1.15.2,<2"
shapely = ">=2.1.2,<3"
cwltool = ">=3.2.20260413085819,<4"
skopeo = ">=1.24.0,<2"
jupyterlab = ">=4.6.3,<5"
xarray = ">=2026.7.0,<2027"
zarr = ">=3.3.0,<4"

[environments]
dev = ["dev", "docs"]

[feature.dev.dependencies]
pytest = ">=9.1.1,<10"
prek = ">=0.5.1,<0.6"
pytest-cov = ">=7.1.0,<8"
typst = ">=0.14.2,<0.15"

[feature.docs.dependencies]
quarto = ">=1.9.38,<2"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
stac-valid = ">=4.5.2, <5"

[activation.env]
PATH = "$PIXI_PROJECT_ROOT/scripts:$PATH"
