project:
  type: book

book:
  title: "Heatwise interoperability demonstration"
  author: "Hannes Neuschmidt"
  date: 2026-09-07
  chapters:
    - href: index.qmd
    - href: requirements.qmd
    - href: setup.qmd
    - part: "Software Products"
      identifier: part-software
      chapters:
      - href: software_products/hotspots.qmd
        text: Hotspots
      - href: software_products/inertia.qmd
        text: Apparent Thermal Inertia
      - href: software_products/combined_hotspots_materials.qmd
        text: Combined Hotspots and Materials
      - href: software_products/unmixing.qmd
        text: HySUPP Unmixing
      - href: software_products/lcz_preprocessing.qmd
        text: LCZ Preprocessing
      - href: software_products/lcz_patch_extraction.qmd
        text: LCZ Patch Extraction
      - href: software_products/lcz_classification.qmd
        text: LCZ Classification
      - href: software_products/lcz_pipeline.qmd
        text: LCZ Full Pipeline

