project:
  type: default
  render:
    - software_products/hotspots.qmd
    - software_products/inertia.qmd
    - software_products/combined_hotspots_materials.qmd
    - software_products/unmixing.qmd
    - software_products/lcz_preprocessing.qmd

format:
  ipynb: default
