---
title: Introduction
label: sec-introduction
---

# Introduction

This technical note showcases the software deliverables produced by High-resolution Enhanced Analysis Tool for Urban Hyperspectral and Infrared Satellite Evaluation (HEATWISE)
and their adherence to interoperability standards.
All software is provided as Earth Observation Application Package (EOAP) as described by the [OGC Best Practice for Earth Observation Application Package](http://www.opengis.net/doc/BP/eoap/1.0).
An EOAP consists of a Common Workflow Language (CWL) document which describes the inputs, outputs and processing steps of the software, with software made available in a container image referenced
in the CWL document.
<!-- TODO: Check if we need to use a proper cross-reference here for PDF output.-->
The requirements imposed by the OGC Best Practice are detailed in @sec-requirements.

The HEATWISE processors have been made to conform to the best practice by two methods.

1. Hand-written CWL, manually ensuring that all requirements of the best practice are implemented.
1. Using [`xcengine`](https://xcube-dev.github.io/xcengine/), a tool for converting Jupyter Notebooks into EOAPs. Xcengine generates the CWL document from an annotated Jupyter notebook.


## Heatwise Software

The following EOAPs have been created in the context of Heatwise:


| Number| Name | Description | Source Code | Type |
|------:|:-----|:------------|:------------|:------|
| 1     | LST Hotspot Detection | Hotspot detection algorithm is based on an ensemble machine learning (ML) framework that combines predictions from multiple regression models through majority voting. Its objective is to identify spatially coherent clusters of pixels whose LST are significantly higher (hotspots) or lower (coldspots) than would be expected given the thermal characteristics of their surrounding neighbourhood. <!-- newline comment
--> | <https://github.com/ESA-Heatwise/lstm-wp3-products/tree/main/products/hotspots> | xcengine |
| 2     | Apparent Thermal Inertia | Apparent Thermal Inertia from day/night LST and reflectance inputs. | <https://github.com/ESA-Heatwise/lstm-wp3-products/tree/main/products/inertia> | xcengine |
| 3     | Combined Hotspots and Urban Materials | Combines hotspot and material information using the Copernicus Land Monitoring Service Urban Atlas (UA) dataset as the basis layer. | <https://github.com/ESA-Heatwise/lstm-wp3-products/tree/main/products/ua> | xcengine |
| 4     | PFTNC | Phytoplankton Functional Types Now-casting | <https://github.com/ESA-Heatwise/heatwise-pftnc> | xcengine |
| 5     | HSI + LST preprocessing | Stage 1 of the HEATWISE LCZ pipeline: turns raw per-city HSI (CHIME-like) + Sentinel-2 (+ optional LST) inputs into processed, analysis-ready rasters. | <https://github.com/ESA-Heatwise/heatwise-hsi-lst-prep> | manual |
| 6     | Patch extraction | Stage 2 of the HEATWISE LCZ pipeline: extracts aligned image patches from a city's Sentinel-2, hyperspectral, and optional LST/PCA products using polygon-based LCZ labels. | <https://github.com/ESA-Heatwise/heatwise-patch-extraction> | manual |
| 7     | LCZ classification | Stage 3 of the HEATWISE LCZ pipeline: the LCZ_HMSSNet model, its training/ evaluation loop, and sliding-window whole-scene inference. | <https://github.com/ESA-Heatwise/heatwise-lcz-classification> | manual |
| 8     | LCZ pipeline | Chain from Stage 1 to Stage 3 of the Heatwise LCZ pipeline. | <https://github.com/ESA-Heatwise/heatwise-lcz-pipeline> | manual |
| 9     | HySUPP Unmixing | HEATWISE HySUPP-based supervised unmixing processor. | https://github.com/ESA-Heatwise/heatwise-hysupp-unmixing | manual |

: Earth Observation Application Packages produced by HEATWISE {#tbl-software-products}

## Demonstration

This technical note contains a demonstration of adherence to interoperability best practice. All software products listed in @tbl-software-products are shown to adhere to [OGC Best Practice for Earth Observation Application Package](http://www.opengis.net/doc/BP/eoap/1.0). The requirements and how each requirement is demonstrated are discussed in @sec-requirements.

The demonstration makes use of several tools for validating aspects of the best practice. An overview of the tools used is given in @tbl-tools. All tools are installed by following the instructions in @sec-installation.



| Tool | Description | Purpose |
|:------|:-------------|:---------|
|[cwltool](https://cwltool.readthedocs.io/en/latest/index.html) | The reference implementation of the [Common Workflow Language open standards](https://www.commonwl.org/) |  Used to validate CWL documents and execute EOAPs as CWL workflows |
| [stac-validator](https://github.com/StacLabs/stac-validator) | A tool to validate [SpatioTemporal Asset Catalog (STAC)](https://github.com/radiantearth/stac-spec) json files. | Used to validate the STAC documents generated by the EOAPs.|
| [yq](https://github.com/kislyuk/yq) | A yaml-frontend to the [`jq`](https://jqlang.org/) command-line tool for querying and subsetting JSON documents. <br><br> **Note**: There are (at least) two yaml processors based on jq syntax named `yq`. In this demonstration, the implementation by Andrey Kislyuk is used which is available as `yq` on [conda-forge](https://anaconda.org/channels/conda-forge/packages/yq/overview). | Used to extract parts of the CWL (yaml) and STAC (json) documents to verify that required fields are filled and structures correct. The `yq` commands are wrapped as scripts, and are [available in the Github repository](https://github.com/ESA-Heatwise/heatwise-interoperability-demonstration/tree/main/scripts). |
| [skopeo](https://github.com/podman-container-tools/skopeo) | A tool to interact with container images and repositories. | Used to check whether the container image referenced in the EOAP CWL documents are available from a remote repository. |

: Tools used in the demonstration {#tbl-tools tbl-colwidths="[20, 40, 40]"}


The demonstrations for each of the EOAPs are documented in the later chapters (part "Software Products") of this technical note.
To reproduce the results, the instructions in @sec-setup must be followed.
Afterwards, the documentation can be re-rendered (generating new demonstration results) as described in @sec-rendering or each of the commands executed by hand.

All scripts used are part of the [same repository](https://github.com/ESA-Heatwise/heatwise-interoperability-demonstration) as this technical note and available in the `scripts` directory.
