name: Deploy site to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: v0.70.2

      - name: install dependencies
        run: |
          pixi install --all

      - name: stage inputs
        run: |
          pixi run stage

      - name: Render site
        run: |
          pixi run render-website

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy-website:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  upload-pdf:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: render PDF
        run: |
          pixi run render-pdf
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: technical-note
          path: _book_pdf/Heatwise-interoperability-demonstration.pdf
          overwrite: true
          archive: false
          if-no-files-found: warn
